[package]
name = "GameofLife"
version = "0.0.1"
authors = ["Julian Melendez"]

[dependencies]
rand = "0.8.5"
array2d = "0.2.1"

[profile.release]
opt-level = 3

[[bin]]
name = "conways"
path = "src/conways.rc"
